vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.o.clipboard = 'unnamedplus'
vim.o.number = true;
vim.o.relativenumber = true;
vim.o.signcolumn = 'yes'
vim.o.updatetime = 300
vim.o.termguicolors = true
vim.o.mouse = 'a'
vim.o.expandtab = true
vim.opt.list = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
